### PR TITLE
Add CTR mode of operation

### PR DESCRIPTION
**Pull request by nikeee**
Code to check both new cipher texts:

```bash
# cipertext.7
echo "c0ldc0ffee" | python3 encrypt.py -e --nonce 0123456789ABCDEF0123456789ABCDEF -m CTR examples/message.bin examples/ciphertext.7-check > /dev/null
echo "c0ldc0ffee" | python3 encrypt.py -d --nonce 0123456789ABCDEF0123456789ABCDEF -m CTR examples/ciphertext.7-check examples/message.bin-check > /dev/null

sha256sum examples/message.bin examples/message.bin-check \
          examples/ciphertext.7-check examples/ciphertext.7


# cipertext.8
echo "Computerphile" | python3 encrypt.py -e --nonce this_is_a_Number_only_used_ONCE. -m CTR examples/message.bin examples/ciphertext.8-check > /dev/null
echo "Computerphile" | python3 encrypt.py -d --nonce this_is_a_Number_only_used_ONCE. -m CTR examples/ciphertext.8-check examples/message.bin-check > /dev/null

sha256sum examples/message.bin examples/message.bin-check \
          examples/ciphertext.8-check examples/ciphertext.8
```

Happy to hear feedback!

### CODE REVIEW

**Comment by mikepound** [comment]
Looking good! I've done a bit of testing, a few minor points i think you could tweak:

- can you add '-n' to the argparse definition to make it similar to iv and mode

- Your way of inputting nonces as parameters is fine, it's also consistent with the other modes. This said, it might make more sense (and be a little easier on the command line) if nonces were passed as integers, simply because this is how they're usually used in practice anyway. I'd suggest you try to parse the command line arg as an int, and if that fails (except ValueError) then maybe encode UTF-8 to bytes. This also means that --nonce 3 would be valid. If you end yup with bytes that are shorter than the nonce size, I think prepending zeros is OK as well - it's up to a user not to reuse a nonce here. Once you've parsed the int you can use nonce.to_bytes(nonce_length, "big") to convert into a nonce of the appropriate size. Does this make sense?

- If you do change the above, you can recreate new example ciphertexts with shorter nonce examples.

- Typo "Padding e_rror"
- Typo "length (ust be" but you might be able to remove this error anyway if you're padding nonces.

- Often in CTR we wouldn't need to use padding since it's a stream cipher. This said the alternative would require you to e.g. store the length of the data in the opening 4-8 bytes, and we don't have access to the length of the data at the start of the file due to the way the iterators are coded. I suggest we stick with your implementation.

**Comment by nikeee** [comment]
Thanks for the feedback!

> Does this make sense?

Sounds good.

> Often in CTR we wouldn't need to use padding since it's a stream cipher.

You are right. It looked like it was operating like ECB on the wikipedia schematic, and therefore a padding was needed. Due to the xor block being indeendent from the cipher/plain text, it really is just a stream cipher.

> I suggest we stick with your implementation.

You made me question the whole padding thing. Why don't just do no padding? If a block is found that has `len(block) < block_size`, do normal encryption by xoring the cipher stream and trim the result to `[:len(block)]` afterwards. As it should only happen in the last block, I don't see a problem. If `len(block) == block_size`, we do the same, but without the trimming part.

With no padding, encryption and decryption should be identical and we don't even have to know whether wer're at the end of the file, since the last block is the only block with `len(block) < block_size`.
Or am I missing something here?

I'll implement these requests soon.

**Comment by mikepound** [comment]
I think you're right, if you simply crop the last block if it's short, and only output the crop to the file, that should allow CTR to work with no padding at all. Feel free to test this approach and use it if it works better!

**Comment by nikeee** [comment]
I implemented your changes and added a sample, so that we use a utf-8 encoded sample as well as a plain number.

You can use this for validation:
```bash
# cipertext.7
echo "c0ldc0ffee" | python3 encrypt.py -e --nonce 42 -m CTR examples/message.bin examples/ciphertext.7-check > /dev/null
echo "c0ldc0ffee" | python3 encrypt.py -d --nonce 42 -m CTR examples/ciphertext.7-check examples/message.bin-check > /dev/null

sha256sum examples/message.bin examples/message.bin-check \
          examples/ciphertext.7-check examples/ciphertext.7


# cipertext.8
echo "Computerphile" | python3 encrypt.py -e --nonce this_is_a_number_used_only_once. -m CTR examples/message.bin examples/ciphertext.8-check > /dev/null
echo "Computerphile" | python3 encrypt.py -d --nonce this_is_a_number_used_only_once. -m CTR examples/ciphertext.8-check examples/message.bin-check > /dev/null

sha256sum examples/message.bin examples/message.bin-check \
          examples/ciphertext.8-check examples/ciphertext.8

# cipertext.9
echo "Computerphile" | python3 encrypt.py -e --nonce 1337 -m CTR examples/message.bin examples/ciphertext.9-check > /dev/null
echo "Computerphile" | python3 encrypt.py -d --nonce 1337 -m CTR examples/ciphertext.9-check examples/message.bin-check > /dev/null

sha256sum examples/message.bin examples/message.bin-check \
          examples/ciphertext.9-check examples/ciphertext.9
```

**Comment by mikepound** [comment]
Working nicely! Very nice decrypt function :) One minor suggestion, I recommend making use of eof to signal the last block rather than length. E.g. replace:

if len(data) < self.block_size:
    assert eof, 'Only the last block of a file can be shorter than the block size'
    xor_block = xor_block[:len(data)]

With

if eof and len(data) < self.block_size:
    xor_block = xor_block[:len(data)]

Does much the same thing but is consistent with the other modes.

**Comment by nikeee** [comment]
Done in c7b0963.

**Comment by nikeee** [comment]
I also implemented CFB and OFB modes in a separate branch:
https://github.com/nikeee/feistel/blob/ofb-cfb/modes.py#L162-L240

Is this a thing that is relevant for this repository? The readme only mentions CBC and CTR modes.

**Comment by mikepound** [comment]
It's very relevant :) I've been a bit tied up today with work and tomorrow is also busy, but feel free to put in another pull request for this and i'll take a look as soon as I can.

**Comment by nikeee** [comment]
I just saw the video on this code and it reminded me of this PR which I totally forgot. Let's see if we can get the CFB and OFB in here.

**Pull request merged**
