### PR TITLE
Added CBC mode of operation

### PR DESCRIPTION
**Pull request by LvMalware**
I just added the CBC mode. And the command line options for it.

### CODE REVIEW

**Comment by mikepound** [comment]
Great! I was hoping someone would look into this :)

I've had a look through, mostly it's great I think we shouild just look briefly at IV usage. A few things I noticed:

- If no -i flag is used you will get a NoneType exception when checking len(args.iv), this could be a preliminary check and a different error message.
- You don't need to call bytes() around the encode function for the IV as it returns bytes.
- Because you check the length of iv prior to encoding, it can actually get bigger. Because we're encoding using UTF-8, some characters e.g. é are more than one byte. Length of IV as a string can be 64, but then once encoded the bytes it might be 64-67 bytes. This works anyway as it happens because I think the xor function drops some bytes but I'm not sure. In any case, I'd simply encode to bytes first, then check the length. Then someone that wanted to use é would simply type one fewer characters.

I'm trying to work out whether it's better to supply an IV on the command line like in your implementation, or have CBC generate one and prepend it to the file. Your approach is more consistent from an interface point of view, so I think it's fine for this toy example. I think the main issue is because we're using a large block size it's a bit unwieldy from the command line. I don't think there's a super elegant way around this.

As a last thing, it might be good to add 3 more encryption examples of message.bin with varied IV and key combinations?

**Comment by LvMalware** [comment]
Indeed. I'll take a look at this IV issue, it might be interesting to add an option to generate the IV if it is not informed (it would be more practical).
And I can add the examples as well.

**Comment by LvMalware** [comment]
Should I close this pull request, fix this issue and then open a new one? Or would just fixing it be better? (Because I think it would get a little polluted with all my commits )

**Comment by mikepound** [comment]
There's no need to close this pull request. Historically people would have removed the commits and recommitted everything once at the end, but actually there's a lovely recent "Squash and merge" feature that I have access to so I can combine this into a single commit during the merge.

Feel free to explore the generation of an iv (os.urandom(64) would be fine) as an alternative. This would probably have to be stored as a block in the output, so I guess the ciphertext would be 64 bytes longer than the message (and maybe longer still given padding) but this is ok. The decrypt would also need to take the first 64 bytes as IV and not as ciphertext too.

One issue is I don't see this being as consistent with CTR mode because the nonce is probably more easily passed as a command line parameter. Generating random nonces isn't a good idea, but they are usually short at least.

**Comment by LvMalware** [comment]
Now the IV is optional on command line and will be prepended to the cipher texts.
Also, I added the examples of cipher texts (but it created a confict. :( )

**Comment by mikepound** [comment]
I'll have a another look later today. The conflict is probably because I recently committed a change that removed ciphertext.4, and you committed one that changed it. I'll see if I can fix it, but one thing you can do I think is merge my master branch back into yours, you'll get the deletion, and then you can put the file back in.

**Comment by LvMalware** [comment]
There you go. Merge conflict resolved.

**Comment by mikepound** [comment]
Looking good! All of your ciphertext examples decrypted fine for me. It looks like if you pass an IV during decrypt it's ignored because it reads from the file instead? I think this is fine - I'm not sure throwing an error is helpful.

**Pull request merged**
